In [1]:
# slope is for linear equation and it is constant.
# Derivative is used for non linear equation and it is a function.

In [2]:
# Matrix Basics

import numpy as np

revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

# profit = revenue - expenses
# 
price_per_unit = np.array([1000,400,1200])
# by default it considers like that 
#[1000,400,1200]
# [1000,400,1200]
# [1000,400,1200]
# Above is called broadcasting.

# y--> product
# x--> year 
units = np.array([[30,40,50],
                  [5,10,15],
                  [2,5,7]])

price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [4]:
# in this it not do numpy broadcasting.
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

# Loss Or Cost Function

In [8]:
# during model compile we use the lost function.

# TENSORLFOW LOSS VALUE EXAMPLES
# 1. sparse_categorical_crossentropy
# 2.binary_crossentropy
# 3.categorical_crossentropy
# 4.mean_absolute_error
# 5.mean_squared_error

# Squared helps to converge gradient descent in a better way.

In [10]:
# Binary Classification

# Based on age and affordability , come up with a function that can predict if person will buy insurance or not.

# Individual error is called as loss while the mean of like that is called as cost.

# i epoch is going through the all samples 1 time.

# log loss is also called binary cross entropy. --> -(1/n)*(  sigma( yilog(y^ i) + (1-yi) )*log(1-y^ i) )


# NOTE : for logistic regression we used log loss not the mean squared error.

# read article of mr. rajesh on towards data science for better understanding.


In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_true,y_predicted):
    total_error = 0;
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error:",total_error)
    mae = total_error/len(y_true)
    print("Mean Absolute error :",mae)
    return mae

In [3]:
mae(y_true,y_predicted)

Total error: 2.5
Mean Absolute error : 0.5


0.5

In [4]:
# gives real difference
y_true-y_predicted

array([-0.7, -0.3,  1. ,  0. , -0.5])

In [5]:
np.abs(y_true-y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
mae1 = np.mean(np.abs(y_true-y_predicted))
mae1

0.5

In [7]:
tot_error = np.sum(np.abs(y_true-y_predicted))
tot_error

2.5

In [8]:
# while manually calculating log function , you should take care that you should avoid log(0) --> inf.
# so whenever you encounter value as 0 so u should make it like that --> 0..0000001 i.e cose to 0.
# so we have a epsilon for that.

In [9]:
np.log([0.0000000001])

array([-23.02585093])

In [18]:
eplison = 1e-15
# np.log(y_predicted) -> give inf values

In [23]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
# to avoid 0.
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [24]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [31]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [34]:
# log_error_func = -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new) )
# ----> 1 log_error_func = -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new) )
# TypeError: unsupported operand type(s) for -: 'int' and 'list'

# so we should do
y_predicted_new = np.array(y_predicted_new)
log_error_func = -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new) )
log_error_func

17.2696280766844

In [37]:
# np.square(3)
def log_loss(y_true,y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new) )

In [38]:
log_loss(y_true,y_predicted)

17.2696280766844

In [40]:
mse = np.mean(np.square(y_true-y_predicted))
mse 

0.366