<a href="https://colab.research.google.com/github/akkuhanu/DeepLearning/blob/main/DeepLpractice/Gradient_Descent_dl12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GRADIENT DESCENT

In [4]:
# Important for interviews. (Core of ML Domain)
# suppose  y = m1*a + m2*b + m3*c +...+ d.
# in order to where m1 ,m2,m3.... are variables we give input.
# BUT a,b,c,d... are constants to find their values we use gradient descent.



In [5]:
# steps 

# w1 = w1 - something
# w1 = w1 - learningrate*d/dw1
# d/dw1--> derivative of loss w.r.t to w1.

# look for convex loss function --> https://am207.github.io/2017/wiki/gradientdescent.html
# we find the values that correspond to min. loss.

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_csv("https://raw.githubusercontent.com/akkuhanu/DeepLearning/main/DeepLpractice/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [9]:
len(x_train)

22

In [10]:
df.shape

(28, 3)

In [11]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age']/100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100


In [12]:
x_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [13]:
# scaling helps to bring age and affordability on the same scale.


In [14]:
model = keras.Sequential(
    [
        keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
    ]
)
# note it is zeros not zeroes
# binary crossentropy is same as log loss.

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

model.fit(x_train_scaled,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 13ms/step - loss: 0.5321 - accuracy: 0.7273
Epoch 2502/5000
1/1 [==============================] - 0s 16ms/step - loss: 0.5321 - accuracy: 0.7273
Epoch 2503/5000
1/1 [==============================] - 0s 15ms/step - loss: 0.5321 - accuracy: 0.7273
Epoch 2504/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.5320 - accuracy: 0.7273
Epoch 2505/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5320 - accuracy: 0.7273
Epoch 2506/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5320 - accuracy: 0.7273
Epoch 2507/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5319 - accuracy: 0.7273
Epoch 2508/5000
1/1 [==============================] - 0s 14ms/step - loss: 0.5319 - accuracy: 0.7273
Epoch 2509/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5318 - accuracy: 0.7273
Epoch 2510/5000
1/1 [===========================

In [15]:
model.evaluate(x_test_scaled,y_test)

1/1 [==============================] - 0s 245ms/step - loss: 0.3550 - accuracy: 1.0000


[0.35497748851776123, 1.0]

In [16]:
model.predict(x_test_scaled)
# if greater than 0.5 means buy the insurance.

array([[0.7054848 ],
       [0.35569546],
       [0.16827846],
       [0.47801173],
       [0.7260697 ],
       [0.8294984 ]], dtype=float32)

In [17]:
x_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [18]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [19]:
coef , intercept = model.get_weights()
print("Coeffecients",coef,"\n Bias Intercept:",intercept)

Coeffecients [[5.0608673]
 [1.4086503]] 
 Bias Intercept: [-2.913703]


In [20]:
import math
# takes one value
def sigmoid(x):
    return 1/(1+math.exp(-x))
sigmoid(10)

0.9999546021312976

In [21]:
# below code is like a derivation or you can say that we made the model with tensorflow help.
def prediction_function(age,affordability):
    age = age/100
    weighted_sum = coef[0]*age + coef[1]*affordability + intercept
    return sigmoid(weighted_sum)
prediction_function(47,1)

0.705484819775958

In [22]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [23]:
# passing a loss threshold meanibg stop when it matches.
def gradient_descent(age,affordibility,y_true,epochs,loss_thresold):
    # w1,w2,bias
    # here age is numpy array and afforability also and numpy array
    age = np.array(age)
    age = age/100 # scaling of age
    affordibility = np.array(affordibility)
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range (epochs):
        weighted_sum = w1*age + w2*affordibility + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true,y_predicted)
        # d/dw1 ---> 1/n( summasion( xi* (y^i - yi) ) ) where xi is age or like factors.
#         in numpy for multiply us np.dot
        deriv_w1 = np.mean( np.dot( np.transpose(age) ,(y_predicted-y_true) ) )
        deriv_w2 = np.mean( np.dot( np.transpose(affordibility) ,(y_predicted-y_true) ) )
        deriv_bias = np.mean(y_predicted-y_true)
        
        w1 = w1 - rate*deriv_w1
        w2 = w2 - rate*deriv_w2
        bias = bias - rate*deriv_bias
        
        print(f'Epoch:{i},w1:{w1},w2{w2},bias:{bias},loss:{loss}')
        if(loss<=loss_thresold):
            break
    return w1,w2,bias

In [24]:
gradient_descent(x_train['age'],x_train['affordibility'],y_train,500,0.4631)

Epoch:0,w1:0.4479679363438934,w2-0.13634124132036352,bias:-0.11341867736368583,loss:0.7113403233723417
Epoch:1,w1:0.9812558612136683,w20.9668377724411847,bias:-0.1110018417733685,loss:0.6847035508118
Epoch:2,w1:0.5432860438890404,w20.004384593070066445,bias:-0.21131519392809667,loss:0.6835888783135032
Epoch:3,w1:1.031660503214578,w20.9617958944318464,bias:-0.2126594225528631,loss:0.6672013121666804
Epoch:4,w1:0.6643520021310426,w20.10437614882580182,bias:-0.3044688785930035,loss:0.6654825340293027
Epoch:5,w1:1.1198293421267327,w20.9599528357847978,bias:-0.30822251315843996,loss:0.6532925028015711
Epoch:6,w1:0.8028502246932971,w20.179991548313022,bias:-0.3936533314399495,loss:0.6511488955709278
Epoch:7,w1:1.2304013077788996,w20.9567360173400518,bias:-0.3992455620331281,loss:0.6412898575315285
Epoch:8,w1:0.9521406008294833,w20.24017212730243642,bias:-0.47950536287644135,loss:0.6388394443962251
Epoch:9,w1:1.3541870964283542,w20.9515313020576354,bias:-0.48666107375165474,loss:0.63049538598

(5.585496109953384, 1.0520504840195588, -2.7686660363765507)

In [25]:
coef , intercept


(array([[5.0608673],
        [1.4086503]], dtype=float32), array([-2.913703], dtype=float32))

In [26]:
# customModel = myNN()
# customModel.fit(x_train_scaled,y_train,epochs=8000,loss_thresold=0.4631)
# customModel.predict(x_test_scaled)

In [30]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    
    def fit(self,x,y,epochs,loss_thresold):
        self.w1,self.w2,self.bias = self.gradient_descent(x['age'],x['affordibility'],y,epochs,loss_thresold)
        
    # passing a loss threshold meanibg stop when it matches.

    def predict(self,x_test):
      weighted_sum = self.w1*x_test['age'] + self.w2*x_test['affordibility'] + self.bias
      return sigmoid_numpy(weighted_sum)

    def gradient_descent(self,age,affordibility,y_true,epochs,loss_thresold):
        # w1,w2,bias
        # here age is numpy array and afforability also and numpy array
        age = np.array(age)
        age = age/100 # scaling of age
        affordibility = np.array(affordibility)
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range (epochs):
            weighted_sum = w1*age + w2*affordibility + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true,y_predicted)
            # d/dw1 ---> 1/n( summasion( xi* (y^i - yi) ) ) where xi is age or like factors.
            #in numpy for multiply us np.dot
            deriv_w1 = np.mean( np.dot( np.transpose(age) ,(y_predicted-y_true) ) )
            deriv_w2 = np.mean( np.dot( np.transpose(affordibility) ,(y_predicted-y_true) ) )
            deriv_bias = np.mean(y_predicted-y_true)
            w1 = w1 - rate*deriv_w1
            w2 = w2 - rate*deriv_w2
            bias = bias - rate*deriv_bias
            print(f'Epoch:{i},w1:{w1},w2{w2},bias:{bias},loss:{loss}')
            if(loss<=loss_thresold):
                break
        return w1,w2,bias

In [31]:
customModel = myNN()
# x_train_scaled['age']
customModel.fit( x_train_scaled , y_train , epochs=800 , loss_thresold=0.4631)


Epoch:0,w1:0.9984209111923338,w20.37673737365828375,bias:-0.0739505736380883,loss:0.678816168870839
Epoch:1,w1:1.0017517758650303,w20.8436042438450847,bias:-0.09498947267405013,loss:0.6661072665747058
Epoch:2,w1:1.002071063085453,w20.5849644110433472,bias:-0.14805175647486063,loss:0.6604101967679624
Epoch:3,w1:1.004706756981319,w20.8251859609999064,bias:-0.1760351517150764,loss:0.6557870443807238
Epoch:4,w1:1.0059766740948566,w20.7207087554209336,bias:-0.2184230986983189,loss:0.6523665184262313
Epoch:5,w1:1.0084063710657871,w20.8526976774635567,bias:-0.24815407398416764,loss:0.6494291449892811
Epoch:6,w1:1.0102377505188804,w20.8189707216126721,bias:-0.2840842602266128,loss:0.646890572424318
Epoch:7,w1:1.0126762971654644,w20.8976079810864801,bias:-0.3133019330839134,loss:0.6446171832493965
Epoch:8,w1:1.0148787625074032,w20.8962739350905107,bias:-0.344855487729369,loss:0.642565194428466
Epoch:9,w1:1.0174192747427695,w20.9480121537041344,bias:-0.3726000991801656,loss:0.6406966244074392
Ep

In [32]:
customModel.predict(x_test_scaled)

2     0.941238
10    0.804179
21    0.526232
11    0.867836
14    0.946220
9     0.968652
dtype: float64