<a href="https://colab.research.google.com/github/akkuhanu/DeepLearning/blob/main/DeepLpractice/prac_desc_grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# To generate random number between 1 to n-1 (both inclusive)
import random
n = 10
print(random.randint(1, n-1))

9


Mini Batch Gradient ---> Intermediate between stochastic and Batch gradient . (in this we take m sample samples such that m>0 and m<n)



In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/akkuhanu/DeepLearning/main/DeepLpractice/homeprices_banglore.csv")
df.sample(5)

area  bedrooms  price
7   3300         4  155.0
3   1521         3   75.0
12  1000         2   38.0
10  1800         3   82.0
17  1540         3   60.0

In [ ]:
y = df['price']

In [ ]:
y

0      39.07
1     120.00
2      62.00
3      75.00
4      51.00
5      38.00
6     135.00
7     155.00
8      50.00
9     167.00
10     82.00
11    140.00
12     38.00
13     40.00
14    101.00
15     42.00
16     48.00
17     60.00
18    102.00
19     32.00
Name: price, dtype: float64

In [ ]:
x = df.drop('price',axis='columns')

In [ ]:
x

area  bedrooms
0   1056         2
1   2600         4
2   1440         3
3   1521         3
4   1200         2
5   1170         2
6   2732         4
7   3300         4
8   1310         3
9   3700         5
10  1800         3
11  2785         4
12  1000         2
13  1100         2
14  2250         3
15  1175         2
16  1180         3
17  1540         3
18  2770         3
19   800         1

In [ ]:
# now i observe that here area has large values where as bedrooms has small values.
# so i want to somehow make these value n relatable range.
# so we shhould perform scaling

from sklearn import preprocessing

sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_x = sx.fit_transform(x)
# scaled_y = sy.fit_transform(y)
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

scaled_x


array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [ ]:
y

0      39.07
1     120.00
2      62.00
3      75.00
4      51.00
5      38.00
6     135.00
7     155.00
8      50.00
9     167.00
10     82.00
11    140.00
12     38.00
13     40.00
14    101.00
15     42.00
16     48.00
17     60.00
18    102.00
19     32.00
Name: price, dtype: float64

In [ ]:
y.shape

(20,)

In [ ]:
# y.shape --> (20,)
# this implies it is a 1-D array with 20 columns and 1 row

# so want it to convert into 2d array.

# scaled_y = sy.fit_transform(y.reshape(y.shape,1))
# AttributeError: 'Series' object has no attribute 'reshape'


scaled_y = sy.fit_transform(df['price'].values.reshape(df.shape[0],1))
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [24]:
# To find the range / permutation / to get m (m>0 && m<n) numbers from 1 to n , we used below function.

np.random.permutation(20)

array([ 7,  4,  8, 13, 14,  6,  3,  1, 12, 16, 10,  2,  5,  0, 18,  9, 17,
       11, 15, 19])

In [ ]:
def mini_batch(x,y,m,learning_rate=0.5,epochs):

  total_samples = x.shape[0]
  no_of_features = x.shape[1]

  if m>total_samples:
    m = total_samples
  
  w = np.ones(shape=(no_of_features))
  b = 0

  cost_list = []
  epoch_list = []

  for i in range(epochs):

    q = np.random.permutation(m)

    sum = 0;
    count = 0;
    for j in q:

      # w_grad = -(2/total_samples)*()
      # b_grad = -(2/total_samples)*()
      
      sum += np.square(sample_y - y_predicted)
      count++

      w = w - w_grad*learning_rate
      b = b - b_grad*learning_rate

    cost = sum/count

    if i%100==0 :

      cost_list.append(cost)
      epoch_list.append(i)

  return w,b,cost,cost_list,epoch_list



